version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"

  server:
    build:
      context: ./server
    ports:
      - "3002:3001"

  python_service:
    build:
      context: ./python_service
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
